---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/mischiefs"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/sites/assets.tobys.cloud"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/sites/page-404"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/sites/www.toby.codes"
    schedule:
      interval: "daily"
