---
apiVersion: v1
kind: Service
metadata:
  name: petitions-exporter
  namespace: metrics
  labels:
    app: petitions-exporter
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: petitions-exporter
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petitions-exporter
  namespace: metrics
spec:
  selector:
    matchLabels:
      app: petitions-exporter
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: petitions-exporter
    spec:
      containers:
      - name: app
        image: ghcr.io/tlwr/petitions-exporter:latest
        imagePullPolicy: Always

        env:
          - name: PETITIONS_URL
            value: https://petitions-remote.tlwr.workers.dev

        ports:
        - containerPort: 8080

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 15
...
