---
apiVersion: v1
kind: Service
metadata:
  name: petitions-exporter
  namespace: metrics
  labels:
    app: petitions-exporter
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: petitions-exporter
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petitions-exporter
  namespace: metrics
spec:
  selector:
    matchLabels:
      app: petitions-exporter
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: petitions-exporter
    spec:
      containers:
      - name: app
        image: ghcr.io/tlwr/petitions-exporter:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 15
...

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: petitions-tobys-cloud
  namespace: metrics
spec:
  secretName: petitions-tobys-cloud-tls
  dnsNames:
  - petitions.tobys.cloud
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
...

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petitions-tobys-cloud
  namespace: metrics
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
    - hosts:
      - petitions.tobys.cloud
      secretName: petitions-tobys-cloud-tls
  rules:
  - host: petitions.tobys.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: petitions-exporter
            port:
              number: 8080
...
