---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rrdtool-storage
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/data/rrdtool-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ams-metal-01
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rrdtool-storage
spec:
  storageClassName: local-storage
  volumeName: rrdtool-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rrdtool
spec:
  selector:
    matchLabels:
      app: rrdtool
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: rrdtool
    spec:
      containers:
        - name: rrdcached
          image: crazymax/rrdcached:latest
          ports:
            - containerPort: 42217
          env:
            - name: TZ
              value: Europe/Amsterdam
            - name: WRITE_TIMEOUT
              value: '30'
          volumeMounts:
            - mountPath: /data/db
              name: rrdtool-storage
              subPath: db
            - mountPath: /data/journal
              name: rrdtool-storage
              subPath: journal

      volumes:
        - name: rrdtool-storage
          persistentVolumeClaim:
            claimName: rrdtool-storage
...
---
apiVersion: v1
kind: Service
metadata:
  name: rrdtool
  annotations:
    tailscale.com/expose: "true"
spec:
  ports:
    - port: 42217
      targetPort: 42217
  selector:
    app: rrdtool
...
