---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rrdtool-storage
  namespace: metrics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rrdtool
spec:
  selector:
    matchLabels:
      app: rrdtool
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: rrdtool
    spec:
      containers:
        - name: rrdcached
          image: crazymax/rrdcached:latest
          ports:
            - containerPort: 42217
          env:
            - name: TZ
              value: Europe/Amsterdam
          volumeMounts:
            - mountPath: /data
              name: rrdtool-storage

      volumes:
        - name: rrdtool-storage
          persistentVolumeClaim:
            claimName: rrdtool-storage
...
---
apiVersion: v1
kind: Service
metadata:
  name: rrdtool
spec:
  ports:
    - port: 42217
      targetPort: 42217
  selector:
    app: rrdtool
...
