---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mischiefs

images:
  - name: ghcr.io/tlwr/mischiefs
    newTag: &newTag 163776322ecd6684b4c2bcab434b161cc603ad04

resources:
  - namespace.yaml
  - site.yaml
