---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mischiefs

images:
  - name: ghcr.io/tlwr/mischiefs
    newTag: bc8fb4d13af699eaaded4f71705d0ed9f54ede64

resources:
  - namespace.yaml
  - site.yaml
