---
apiVersion: v1
kind: Service
metadata:
  name: stats-tobys-cloud
  namespace: static-sites
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: stats-tobys-cloud
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-tobys-cloud
  namespace: static-sites
spec:
  selector:
    matchLabels:
      app: stats-tobys-cloud
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: stats-tobys-cloud
    spec:
      containers:
      - name: nginx
        image: ghcr.io/tlwr/stats.tobys.cloud:@tag
        command: [/app/server]
        args:
          - -prometheus-url
          - https://prometheus-prod-01-eu-west-0.grafana.net
          - -prometheus-basic-auth
          - $(PROM_BASIC_AUTH)
          - -prometheus-read-path
          - /api/prom
        env:
          - name: PROM_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: stats-tobys-cloud-grafana
                key: prometheus-basic-auth
        ports:
        - containerPort: 8080
...

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stats-tobys-cloud
  namespace: static-sites
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  tls:
    - hosts:
      - stats.tobys.cloud
      secretName: stats-tobys-cloud-tls
  rules:
  - host: stats.tobys.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stats-tobys-cloud
            port:
              number: 8080
...
