---
apiVersion: v1
kind: Service
metadata:
  name: www-toby-codes
  namespace: static-sites
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: www-toby-codes
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-toby-codes
  namespace: static-sites
spec:
  selector:
    matchLabels:
      app: www-toby-codes
  replicas: 2
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: www-toby-codes
    spec:
      containers:
      - name: app
        image: ghcr.io/tlwr/www.toby.codes:@tag
        ports:
        - containerPort: 8080
...

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-toby-codes
  namespace: static-sites
spec:
  secretName: www-toby-codes-tls
  dnsNames:
  - toby.codes
  - www.toby.codes
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
...

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www-toby-codes
  namespace: static-sites
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
    - hosts:
      - toby.codes
      - www.toby.codes
      secretName: www-toby-codes-tls
  rules:
  - host: toby.codes
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: www-toby-codes
            port:
              number: 8080
  - host: www.toby.codes
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: www-toby-codes
            port:
              number: 8080
...
