---
apiVersion: v1
kind: Service
metadata:
  name: www-tobys-cloud
  namespace: static-sites
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: www-tobys-cloud
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-tobys-cloud
  namespace: static-sites
spec:
  selector:
    matchLabels:
      app: www-tobys-cloud
  replicas: 2
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: www-tobys-cloud
    spec:
      containers:
      - name: nginx
        image: ghcr.io/tlwr/www.tobys.cloud:@tag
        ports:
        - containerPort: 80
...

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-tobys-cloud
  namespace: static-sites
spec:
  secretName: www-tobys-cloud-tls
  dnsNames:
  - tobys.cloud
  - www.tobys.cloud
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
...

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www-tobys-cloud
  namespace: static-sites
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
    - hosts:
      - tobys.cloud
      - www.tobys.cloud
      secretName: www-tobys-cloud-tls
  rules:
  - host: tobys.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: www-tobys-cloud
            port:
              number: 80
  - host: www.tobys.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: www-tobys-cloud
            port:
              number: 80
...
