---
apiVersion: v1
kind: Service
metadata:
  name: stats-tobys-cloud
  namespace: sites
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: stats-tobys-cloud
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-tobys-cloud
  namespace: sites
spec:
  selector:
    matchLabels:
      app: stats-tobys-cloud
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: stats-tobys-cloud
    spec:
      containers:
      - name: nginx
        image: ghcr.io/tlwr/stats.tobys.cloud:@tag
        command: [/app/server]
        args:
          - -prometheus-url
          - https://grafana-cloud-remote.tlwr.workers.dev
          - -prometheus-basic-auth
          - $(PROM_BASIC_AUTH)
          - -prometheus-read-path
          - /api/prom
        env:
          - name: PROM_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: stats-tobys-cloud-grafana
                key: prometheus-basic-auth
        ports:
        - containerPort: 8080
...
