---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: acceptance-tests
spec:
  schedule: '*/30 * * * *'
  concurrencyPolicy: Replace

  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 3600

      template:
        spec:
          serviceAccountName: acceptance-tests

          containers:
            - name: tests
              image: ghcr.io/tlwr/www-tobys-cloud-acceptance:latest
              workingDir: /acceptance
              command:
                - bundle
                - exec
                - rspec
                - --format=documentation
              env:
                - name: DISCORD_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: discord
                      key: webhook-url

          restartPolicy: Never

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acceptance-tests

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: acceptance-tests
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: acceptance-tests
subjects:
  - kind: ServiceAccount
    name: acceptance-tests
roleRef:
  kind: Role
  name: acceptance-tests
  apiGroup: rbac.authorization.k8s.io
