---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: acceptance-tests
spec:
  schedule: '*/30 * * * *'
  concurrencyPolicy: Replace

  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 3600

      template:
        spec:
          containers:
            - name: tests
              image: ghcr.io/tlwr/www-tobys-cloud-acceptance:latest
              workingDir: /acceptance
              command:
                - bundle
                - exec
                - rspec
                - --format=documentation
              env:
                - name: DISCORD_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: discord
                      key: webhook-url

          restartPolicy: Never
...
