---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sites

resources:
  - namespace.yaml

  - assets-tobys-cloud.yaml
  - page-404.yaml
  - stats-tobys-cloud.yaml
  - www-toby-codes.yaml
  - www-tobys-cloud.yaml

  - acceptance-tests.yaml
