---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sites

images:
  - name: ghcr.io/tlwr/assets.tobys.cloud
    newTag: &newTag 956529e7c18f422d3b1a71469807b02910a883e3
  - name: ghcr.io/tlwr/page-404
    newTag: *newTag
  - name: ghcr.io/tlwr/www-tobys-cloud-acceptance
    newTag: *newTag
  - name: ghcr.io/tlwr/www-tobys-cloud-acceptance
    newTag: *newTag
  - name: ghcr.io/tlwr/www.tobys.cloud
    newTag: *newTag

  - name: ghcr.io/tlwr/www.toby.codes
    digest: 'sha256:c44ab922b414a680b8bc7c4e734f176eb43b161ad401b25d2f9c2210a03f1a87'

  - name: ghcr.io/tlwr/mischiefs
    newTag: 4ec7543d684992fa8a38e462feebeb682b61b98e

resources:
  - namespace.yaml

  - assets-tobys-cloud.yaml
  - page-404.yaml
  - www-toby-codes.yaml
  - www-tobys-cloud.yaml
  - mischiefs.yaml

  - acceptance-tests.yaml
