---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sites

images:
  - name: ghcr.io/tlwr/assets.tobys.cloud
    newTag: &newTag 004ee8ecf8a5cb4665c1e979b9c215e4837d16e5
  - name: ghcr.io/tlwr/page-404
    newTag: *newTag
  - name: ghcr.io/tlwr/stats.tobys.cloud
    newTag: *newTag
  - name: ghcr.io/tlwr/www-tobys-cloud-acceptance
    newTag: *newTag
  - name: ghcr.io/tlwr/www.toby.codes
    newTag: *newTag
  - name: ghcr.io/tlwr/www-tobys-cloud-acceptance
    newTag: *newTag
  - name: ghcr.io/tlwr/www.tobys.cloud
    newTag: *newTag

resources:
  - namespace.yaml

  - assets-tobys-cloud.yaml
  - page-404.yaml
  - stats-tobys-cloud.yaml
  - www-toby-codes.yaml
  - www-tobys-cloud.yaml

  - acceptance-tests.yaml
