---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sites

images:
  - name: ghcr.io/tlwr/www.toby.codes
    digest: 'sha256:14c309a5bed9662ece496b5694cc03b753544c3832f1a1426b2c4120ad2c1ab9'

  - name: ghcr.io/tlwr/www-tobys-cloud-acceptance
    newTag: 956529e7c18f422d3b1a71469807b02910a883e3

  - name: ghcr.io/tlwr/page-404
    digest: 'sha256:da420764fee56123413fbf1e859efeef8cae83d909ba1a5c5d516a5bf7e619f0'

  - name: ghcr.io/tlwr/assets.tobys.cloud
    digest: 'sha256:babe8e00e570df93783d878a8054ec264247193aebce27b36366bad584b67835'

  - name: ghcr.io/tlwr/mischiefs
    digest: 'sha256:9f21a67e254608a6cb3fe9e2837449c9557e5bc817127e99566edd7c54cfebda'

resources:
  - namespace.yaml

  - assets-tobys-cloud.yaml
  - page-404.yaml
  - www-toby-codes.yaml
  - www-tobys-cloud.yaml
  - mischiefs.yaml

  - acceptance-tests.yaml
