---
apiVersion: v1
kind: Service
metadata:
  name: mischiefs
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: mischiefs
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mischiefs
spec:
  selector:
    matchLabels:
      app: mischiefs
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: mischiefs
    spec:
      containers:
      - name: app
        image: ghcr.io/tlwr/mischiefs:latest
        ports:
        - containerPort: 8080
...

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mischiefs
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: haproxy
  rules:
  - host: www.mischiefs.nl
    http:
      paths:
      - backend:
          service:
            name: mischiefs
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: mischiefs.nl
    http:
      paths:
      - backend:
          service:
            name: mischiefs
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - secretName: mischiefs-tls
    hosts:
      - www.mischiefs.nl
      - mischiefs.nl
...
