---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www-tobys-cloud
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    haproxy.org/request-redirect: "www.toby.codes:443"
spec:
  ingressClassName: haproxy
  defaultBackend:
    service:
      name: page-404
      port:
        number: 80
  tls:
  - secretName: www-tobys-cloud-tls
    hosts:
      - tobys.cloud
      - www.tobys.cloud
...
