---
name: bazel

on:
  push:
    paths:
      - 'WORKSPACE'
      - 'BUILD.bazel'
      - 'MODULE.bazel'
      - 'MODULE.bazel.lock'
      - 'deps.bazel'
      - 'go.mod'

      - acceptance/**/*
      - sites/**/*
      - .github/workflows/bazel.yaml

permissions:
  contents: read
  packages: write

jobs:
  run-tests:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.9.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: bazel-test
        run: |
          bazel query 'tests(//...)' | xargs -n 1 bazel test

  push-images:
    needs: run-tests
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.9.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: gchr-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: bazel-run-oci_push
        run: |
          bazel query 'kind(oci_push, //...)' | xargs -n 1 bazel run
