---
name: build-images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: gchr-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: gchr-build-push
        run: |
          make push
