---
name: build-sites

on:
  workflow_run:
    workflows:
      - test-sites
    branches:
      - main
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: [ubuntu-latest]

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
      - name: gchr-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - run: make push
      - run: make push-acceptance-tests
